channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=25.0.1
- pip:
  - mlflow==2.22.1
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.2.2
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
