name: MLflow CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install mlflow==2.22.1 matplotlib==3.8.0 pandas==2.2.2 seaborn==0.13.2 scikit-learn==1.2.2 numpy==1.26.4 scipy==1.15.2 cloudpickle==3.1.1 psutil==7.0.0

    - name: Run MLflow training
      run: |
        mlflow run .

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mlflow-artifacts
        path: mlruns/